module XmlStructWriter

using LightXML
using Base64
using TimeZones
using Printf
using Format
using AbstractXsdTypes

export write_xml

"""
	write_xml(xml_object, xml_path::AbstractString)::Nothing
	write_xml(xml_object, root_name::AbstractString, xml_path::AbstractString)::Nothing

Write the given `xml_object` to the path specified by `xml_path`, with `root_name` as the name of the root element.

The `xml_object` must be of a type generated by the XsdToStruct package. Without `root_name` the root element is named
after the generated module's `__meta.root_name`, which is the root element's name in a document rather than the name
of its Julia type, or, when the module has no `root_name`, after the `__root_name` key of the object's
`__xml_attributes`. Fields renamed by the module's `__meta.XSDMapping` are written under their element names.

The dict in the `__xml_attributes` field of this object must hold the xmlns attribute that gives the name of the
namespace and the corresponding URI of the root element, see [the xml specification](https://www.w3.org/TR/xml-names/#ns-decl)
for details. Please consult the given examples if this is unclear; or inspect an XML loaded with XmlStructLoader, it
will contain all the needed entries in the `__xml_attributes` field.

With this input the written XML is valid according to the schema that was used to generate the struct definitions with
XsdToStruct.

# Examples
Creating an XML from scratch:
```julia-repl
julia> include(joinpath("Example", "Example.jl"))
julia> using .ExampleSchema

julia> using XmlStructWriter

julia> Example1 = ExampleComplexType(
	Element_double=100.22,
	Element_boolean=true,
	Element_integer=-778
)

julia> xml_attributes = Dict(
	"xmlns:xsi"=>"http://www.w3.org/2001/XMLSchema-instance",
	"xsi:schemaLocation"=>"ExampleSchema Example.xsd",
	"xmlns:ExampleSchema"=>"ExampleSchema",
)

julia> document = documentType(
	Example1=Example1,
	Example2="AA99",
	__xml_attributes=xml_attributes
)

julia> write_xml(document, "example.xml")
```

Loading an XML, editing a field, and then writing to a new file, we are using Accessors.jl here which is recommended:
```julia-repl
julia> include(joinpath("Example", "Example.jl"))
julia> using .ExampleSchema

julia> using XmlStructLoader
julia> using XmlStructWriter
julia> using Accessors

julia> xml_original = load("example.xml", ExampleSchema)

julia> xml_new = @set xml_original.Example1.Element_double = -789.123
julia> write_xml(xml_new, "example_new.xml")
```
"""
write_xml(xml_object, xml_path::AbstractString)::Nothing = write_xml(xml_object, root_name(xml_object), xml_path)

function write_xml(xml_object, root_name::AbstractString, xml_path::AbstractString)::Nothing

    # make sure directory exists
    if !isdir(dirname(xml_path))
        mkpath(dirname(xml_path))
    end
    xdoc = XMLDocument()

    name_space_string = first((
        key for
        key in keys(xml_object.__xml_attributes) if occursin("xmlns", key) && !occursin(r"xmlns:xsi|xmlns:xsd", key)
    ))
    name_space = last(split(name_space_string, ":"))
    element_names = field_element_names(generated_module(typeof(xml_object)))
    root_element = create_xml_element(xml_object, "$name_space:$root_name", element_names)

    set_root(xdoc, root_element)
    save_file(xdoc, xml_path)

    return nothing
end

# A generated module is usually included after the caller started running, so its bindings are
# only visible in the latest world.
has_binding(m::Module, name::Symbol)::Bool = Base.invokelatest(isdefined, m, name)
binding(m::Module, name::Symbol) = Base.invokelatest(getglobal, m, name)

# The module XsdToStruct generated `T` in: the innermost enclosing module that carries `__meta`, or
# `nothing` for a type defined elsewhere.
function generated_module(@nospecialize(T::Type))::Union{Module, Nothing}
    m = parentmodule(T)
    while !has_binding(m, :__meta)
        parent = parentmodule(m)
        parent === m && return nothing
        m = parent
    end
    return m
end

function root_name(xml_object)::String
    module_ref = generated_module(typeof(xml_object))
    if !isnothing(module_ref)
        meta = binding(module_ref, :__meta)
        has_binding(meta, :root_name) && return binding(meta, :root_name)
    end
    attributes = xml_object.__xml_attributes
    (isnothing(attributes) || !haskey(attributes, ROOT_NAME_KEY)) && throw(
        ArgumentError(
            "$(typeof(xml_object)) has no generated `__meta.root_name` and its `__xml_attributes` no " *
                "\"$ROOT_NAME_KEY\" key: pass the root element's name to `write_xml`",
        ),
    )
    return attributes[ROOT_NAME_KEY]
end

# The root element's name in the attributes of a document built for a module that lacks `__meta.root_name`.
const ROOT_NAME_KEY = "__root_name"

# Field names mapped back to the element names they were renamed from by `__meta.XSDMapping`, which
# holds the element renames themselves or, as some generators store it, the whole mapping with the
# element renames under "Fields". A flat mapping may rename an element called "Fields", so only a
# dictionary there marks the split form.
function field_element_names(module_ref::Module)::Dict{Symbol, String}
    meta = binding(module_ref, :__meta)
    has_binding(meta, :XSDMapping) || return Dict{Symbol, String}()
    mapping = binding(meta, :XSDMapping)
    get(mapping, "Fields", nothing) isa AbstractDict && (mapping = mapping["Fields"])
    return Dict{Symbol, String}(Symbol(field) => element for (element, field) in mapping)
end

# Types that no generated module carries have no renames.
field_element_names(::Nothing)::Dict{Symbol, String} = Dict{Symbol, String}()

const excluded_names = [:__xml_attributes, :__validated]

function create_xml_element(
        xml_object::AbstractXsdTypes.AbstractXSDComplex,
        name::AbstractString,
        element_names::Dict{Symbol, String},
    )
    @debug "Creating XML element from complex struct $name"
    xml_element = new_element(name)
    xml_property_names = filter(name -> name ∉ excluded_names, Base.invokelatest(propertynames, xml_object))
    for property in xml_property_names
        property_value = Base.invokelatest(getproperty, xml_object, property)
        add_child_element!(xml_element, get(element_names, property, string(property)), property_value, element_names)
    end
    add_attributes!(xml_element, xml_object)
    return xml_element
end

function add_child_element!(xml_element, element_name::AbstractString, value::Any, element_names)::Nothing
    property_element = create_xml_element(value, element_name, element_names)
    add_child(xml_element, property_element)
    return nothing
end

# Bytes are one element carrying base64 text, where any other vector is a field that repeats.
function add_child_element!(xml_element, element_name::AbstractString, value::AbstractVector{UInt8}, element_names)::Nothing
    add_child_element!(xml_element, element_name, Base64.base64encode(value), element_names)
    return nothing
end

function add_child_element!(xml_element, element_name::AbstractString, value::AbstractVector, element_names)::Nothing
    for sub_value in value
        add_child_element!(xml_element, element_name, sub_value, element_names)
    end
    return nothing
end

# nothing to do in this case
add_child_element!(_, ::AbstractString, ::Nothing, _)::Nothing = nothing

function create_xml_element(xml_object, name::AbstractString, _)
    @debug "Creating XML element from $xml_object"
    xml_element = new_element(name)
    set_content(xml_element, generate_xml_string(xml_object))
    add_attributes!(xml_element, xml_object)
    return xml_element
end

function add_attributes!(xml_element, xml_object)::Nothing
    if (
        hasfield(typeof(xml_object), :__xml_attributes) &&
        !isnothing(xml_object.__xml_attributes) &&
        !isempty(xml_object.__xml_attributes)
    )
        attributes = xml_object.__xml_attributes
        if haskey(attributes, ROOT_NAME_KEY)
            attributes = filter(attribute -> first(attribute) != ROOT_NAME_KEY, attributes)
        end
        set_attributes(xml_element, attributes)
    end
    return nothing
end

@inline function generate_xml_string(xml_object::AbstractXsdTypes.AbstractXSDSimpleTypes)::String
    @debug "Generating XML string from $xml_object"
    return generate_xml_string(xml_object.value)
end

function generate_xml_string(xml_object::AbstractXsdTypes.AbstractXSDFloat)::String
    @debug "Generating XML string from $xml_object"
    if AbstractXsdTypes.fraction_digits_check in AbstractXsdTypes.get_restriction_checks(typeof(xml_object))
        max_fraction_digits = AbstractXsdTypes.get_max_fraction_digits(typeof(xml_object))
        xml_object = cfmt("%.$(max_fraction_digits)f", xml_object)
    else
        xml_object = @sprintf("%f", xml_object)
    end
    return xml_object
end

@inline function generate_xml_string(xml_object::AbstractXsdTypes.AbstractXSDString)::String
    @debug "Generating XML string from $xml_object"
    return xml_object.value
end

# A binary XSD type holds decoded bytes, so writing it means encoding them again.
@inline generate_xml_string(xml_object::AbstractXsdTypes.AbstractXSDBinary)::String =
    Base64.base64encode(xml_object.value)

@inline generate_xml_string(bytes::AbstractVector{UInt8})::String = Base64.base64encode(bytes)

@inline function generate_xml_string(s::String)::String
    @debug "Generating XML string from $s"
    return s
end

# The canonical XSD form writes a zero offset as `Z` and a fraction without trailing zeros, where
# `string` prints `+00:00` and pads milliseconds to three digits.
function generate_xml_string(date_time::ZonedDateTime)::String
    text = replace(string(date_time), r"(\.\d*?)0+(?=[+-]\d\d:\d\d$)" => s"\1")
    text = replace(text, r"\.(?=[+-]\d\d:\d\d$)" => "")
    return endswith(text, "+00:00") ? chop(text; tail = 6) * "Z" : text
end

@inline function generate_xml_string(x)::String
    @debug "Generating XML string from $x"
    return string(x)
end

end # module XmlStructWriter
