module XmlStructLoader

using Reexport
using Dates
using TimeZones
using Parsers
using Memoization
using AbstractTrees
using AbstractTrees: parent, isroot
import XmlStructPugixml
using AbstractXsdTypes

include(joinpath("xml_parser", "xml_parser.jl"))
include(joinpath("xml_parser", "lazy_xml_node.jl"))
include("xml_module_utilities.jl")

export load, import_module_from_xml, use_module_from_xml,
    LoadStrategy, ReadAllData, ReadOnAccess, DEFAULT_LOAD_STRATEGY

abstract type LoadStrategy end

"""
    struct ReadAllData <: LoadStrategy end

All data is read from the XML file when it is opened. Slower to return from `load()` on large
documents, but every field access afterward is a plain, already-computed field read.
"""
struct ReadAllData <: LoadStrategy end

"""
    struct ReadOnAccess <: LoadStrategy end

`load()` returns almost immediately; each field's value is parsed from the underlying XML the
first time it is accessed, then cached. Only complex types generated from a choice-free XSD
complex type support this - see the module docstring. Not compatible with `validate=true` (XSD
restriction validation requires the parsed value, which would force materializing every field
anyway - combining the two raises `ArgumentError`).
"""
struct ReadOnAccess <: LoadStrategy end

"""
    const DEFAULT_LOAD_STRATEGY = ReadAllData

Used when `load_strategy` is not specified, for full backward compatibility.
"""
const DEFAULT_LOAD_STRATEGY = ReadAllData

"""
	load(xml_path::AbstractString, module_ref::Module; validate::Bool=true, load_strategy::LoadStrategy=DEFAULT_LOAD_STRATEGY())

Load the given XML file into the structs defined in the given module and return the loaded struct.
The module has to be generated by XsdToStruct.jl.
By default the loader will validate if the data in the given XML conforms to the restrictions specified in the XSD.
To skip this validation the keyword argument `validate`` can be set to false.
Use `load_strategy` to choose between `ReadAllData()` (default, eager) and `ReadOnAccess()` (lazy).

# Examples
```julia-repl
julia> using XmlStructLoader
julia> include(joinpath("path", "to", "xsd", "module.jl"))
julia> using .XsdModule
julia> load(joinpath("path", "to", "xml", "file.xml"), XsdModule)
```
or:
```julia-repl
julia> using XmlStructLoader
julia> include(joinpath("path", "to", "xsd", "module.jl"))
julia> import .XsdModule
julia> load(joinpath("path", "to", "xml", "file.xml"), XsdModule)
```
or to skip validation:
```julia-repl
julia> using XmlStructLoader
julia> include(joinpath("path", "to", "xsd", "module.jl"))
julia> using .XsdModule
julia> load(joinpath("path", "to", "xml", "file.xml"), XsdModule, validate=false)
```
or to load lazily:
```julia-repl
julia> using XmlStructLoader
julia> include(joinpath("path", "to", "xsd", "module.jl"))
julia> using .XsdModule
julia> load(joinpath("path", "to", "xml", "file.xml"), XsdModule; load_strategy=ReadOnAccess(), validate=false)
```
"""
function load(
        xml_path::AbstractString, module_ref::Module;
        validate::Bool = true, load_strategy::LoadStrategy = DEFAULT_LOAD_STRATEGY(),
    )
    local loaded_xml
    open(xml_path) do xml_io
        return loaded_xml = load(xml_io, module_ref; validate = validate, load_strategy = load_strategy)
    end
    return loaded_xml
end

function load(
        xml_io::IO, module_ref::Module;
        validate::Bool = true, load_strategy::LoadStrategy = DEFAULT_LOAD_STRATEGY(),
    )
    return load(xml_io, module_ref, load_strategy; validate = validate)
end

load(xml_io::IO, module_ref::Module, ::ReadAllData; validate::Bool = true) =
    Base.@invokelatest construct_xml_object(xml_io, module_ref, validate = validate)

function load(xml_io::IO, module_ref::Module, ::ReadOnAccess; validate::Bool = true)
    validate && throw(ArgumentError(
        "load_strategy=ReadOnAccess() is not compatible with validate=true: XSD restriction " *
        "validation requires the parsed field value, which would force materializing every " *
        "field anyway, defeating the point of ReadOnAccess. Pass validate=false explicitly.",
    ))
    doc_ptr = XmlStructPugixml.parse_buffer(read(xml_io))
    doc_ptr == C_NULL && error("pugixml failed to parse XML from IO")
    handle = PugixmlDocumentHandle(doc_ptr)  # registered immediately, before anything else can throw
    root_ptr = XmlStructPugixml.root(doc_ptr)
    root_node = LazyNode(root_ptr, handle)
    root_type = Base.@invokelatest module_ref.__meta.root_type
    loaded = Base.@invokelatest root_type(root_node)
    # Match construct_xml_root_object's eager-path bookkeeping: it stamps the document root's own
    # tag name into __xml_attributes["__root_name"] (XmlStructWriter.jl reads this back out to know
    # what to name the root element when serializing). The generic per-node LazyNode constructor
    # (shared by every complex type, root or nested) has no way to know "this particular call is
    # for the document root", so there is no way to inject it there without wrongly stamping every
    # nested field too - this is the one call site that actually knows. The struct is mutable (a
    # LazilyInitializedFields.@lazy requirement), so a direct post-construction field write is safe.
    attrs = getfield(loaded, :__xml_attributes)
    attrs = isnothing(attrs) ? Dict{String, String}() : attrs
    attrs["__root_name"] = name(root_ptr)
    setfield!(loaded, :__xml_attributes, attrs)
    return loaded
end

"""
	load(xml_path::AbstractString, module_path::AbstractString; validate::Bool=true)

Load the given XML file into the structs defined in the given module and return the loaded struct.
The module has to be generated by XsdToStruct.jl.
By default the loader will validate if the data in the given XML conforms to the restrictions specified in the XSD.
To skip this validation the keyword argument `validate` can be set to false.

# Examples
```julia-repl
julia> using XmlStructLoader
julia> load(joinpath("path", "to", "xml", "file.xml"), joinpath("path", "to", "xsd", "module.jl"))
```
"""
function load(
        xml_path::AbstractString, module_path::AbstractString;
        validate::Bool = true, load_strategy::LoadStrategy = DEFAULT_LOAD_STRATEGY(),
    )
    local loaded_xml
    open(xml_path) do xml_io
        return loaded_xml = load(xml_io, module_path; validate = validate, load_strategy = load_strategy)
    end
    return loaded_xml
end

function load(
        xml_io::IO, module_path::AbstractString;
        validate::Bool = true, load_strategy::LoadStrategy = DEFAULT_LOAD_STRATEGY(),
    )
    module_ref = import_module_from_xml(xml_io, module_path)
    return load(xml_io, module_ref; validate = validate, load_strategy = load_strategy)
end

"""
	import_module_from_xml(xml_path::AbstractString, module_path::AbstractString)::Module

Import the module from the .jl files in the module_path and return a reference to this module.
This reference can be passed into the load function.

# Examples
```julia-repl
julia> using XmlStructLoader
julia> module_ref = import_module_from_xml(path/to/xml/file.xml, path/to/module/module.jl)
```
"""
function import_module_from_xml(xml_path::AbstractString, module_path::AbstractString)::Module
    module_ref = open(xml_path) do xml_io
        return import_module_from_xml(xml_io, module_path)
    end
    return module_ref
end

import_module_from_xml(xml_io::IO, module_path::AbstractString)::Module =
    import_module(get_module_file_path(module_path), get_module_symbol(xml_io))

"""
	use_module_from_xml(xml_path::AbstractString, module_path::AbstractString)::Module

Use the module from the .jl files in the module_path and return a reference to this module.
This reference can be passed into the load function.

# Examples
```julia-repl
julia> using XmlStructLoader
julia> module_ref = use_module_from_xml(path/to/xml/file.xml, path/to/module/module.jl)
```
"""
function use_module_from_xml(xml_path::AbstractString, module_path::AbstractString)::Module
    module_ref = open(xml_path) do xml_io
        return use_module_from_xml(xml_io, module_path)
    end
    return module_ref
end

use_module_from_xml(xml_io::IO, module_path::AbstractString)::Module =
    use_module(get_module_file_path(module_path), get_module_symbol(xml_io))

end # module XmlStructLoader
